export const enum Routes {
  Home = "/",
  login = "/login",
  register = "/register",
  forgotPassword = "/forgot_password",
  changePassword = "/change_password",
  password_success = "password_success",
  branch = "branch",
  exchange = "exchange",
  exchange_rate = "exchange_rate",
  interest = "interest",
  language = "language",
  password_change = "password_change",
  app_info = "app_info",
}
